root_folder: "/home/bot/bot/yk/YK_final/courses"
log_folder: "/home/bot/bot/yk/YK_final/log"
course_name: "The Structure and Interpretation of Computer Programs"
db_path: "/home/bot/bot/yk/YK_final/courses_out/metadata.db"
course_code : "CS 61A"
tasks:
  - name: ""
    local: True
    url: "https://cs61a.org/"
    driver_type: "request" # or "playwright"
    # Optional driver options for playwright (only applies when driver_type is "playwright")
    driver_options:
      timeout: 90000  # Playwright timeout in milliseconds (default: 60000 = 60 seconds)
      requests_timeout: 90  # Requests library timeout in seconds (default: 60 seconds)
      max_retries: 3  # Number of retry attempts for both requests and playwright (default: 3)
      block_resources: true  # Block images/fonts/media to speed up loading (default: true)
      headless: true  # Run browser in headless mode (default: true)
      browser_type: "chromium"  # Browser engine: "chromium" (default), "firefox", or "webkit"
                                # Use "firefox" if you get HTTP/2 errors with chromium
      skip_login_pages: true  # Skip pages that require authentication/login (default: true)
      # cookies: null  # Optional: List of cookies for authenticated sessions
                      # Format: [{"name": "session", "value": "abc123", "domain": ".example.com", "path": "/"}]
    roots:
      - url: https://cs61a.org/
        depth: 7
        scraper_type: general_scraper  # or "video_scraper"
      - url: https://www.youtube.com
        depth: 1
        scraper_type: video_scraper
        subtask_folder_path: "youtube"
      - url: https://www.composingprograms.com/
        depth: 10
        scraper_type: general_scraper  # or "video_scraper"
        subtask_folder_path: "textbook"
