root_folder: "/home/bot/bot/yk/YK_final/courses/CS 61A"
log_folder: "/home/bot/bot/yk/YK_final/courses/CS 61A_log"
course_name: "The_Structure_and_Interpretation_of_Computer_Programs"
course_id : "CS61A"
tasks:
  - name: "course_website"
    local: True
    url: "https://cs61a.org/"
    driver_type: "request" # or "playwright"
    roots:
      - url: https://cs61a.org/
        depth: 7
        scraper_type: general_scraper  # or "video_scraper"
      - url: https://www.youtube.com
        depth: 1
        scraper_type: video_scraper
        subtask_folder_path: "youtube"
      - url: https://www.composingprograms.com/
        depth: 10
        scraper_type: general_scraper  # or "video_scraper"
        subtask_folder_path: "textbook"
