input_dir: "/home/bot/bot/yk/YK_final/courses/CS 61A"
output_dir: "/home/bot/bot/yk/YK_final/courses_out/CS 61A_output"
log_folder: "/home/bot/bot/yk/YK_final/courses_out/logs/CS 61A_output"
course_name: "The Structure and Interpretation of Computer Programs"
course_code: "CS 61A"
chunk_db_path : "/home/bot/bot/yk/YK_final/courses_out/course.db"
