# Professor Audio Configuration
# Map course codes to their corresponding professor reference audio files
# The audio files should contain clear samples of the professor speaking
# Recommended: Use the first 20-30 seconds of a lecture where only the professor speaks

# Format:
# COURSE_CODE: /path/to/professor_audio.wav

# Examples:
CS 61A: /home/bot/bot/yk/YK_final/professor_reference/cs61a_professor.wav


# Add more course mappings as needed
# Make sure the audio files are in WAV format and contain clear speech samples